openapi: '3.0.2'
info:
  title: Onboarding
  description: STD22029
  contact:
    email: hei.rado.2@gmail.com
  version: '1.0.0'
servers:
  - url: https://STD22029/v1
 
paths:
  /students:
    get:
      tags:
        - "Student" 
      summary:  all students
      responses:
        '200':
          description: successful 
          content:
            application/json:
              schema:
               $ref: '#/components/schemas/StudentsResponse'
        
        '500': 
          description:  Server Error


 
    post:
      tags:
        - "Student"
      summary: Add Student 
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StudentInput'
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddStudentsResponse'

        '500':
          description:  Server Error
    put:
      tags:
        - "Student"
      summary: Update Student
      parameters:
        - name: studentId
          in: path
          required: true
          description: The ID of the student to update
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StudentInput'
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StudentsResponse'

        '500':
          description:  Server Error

    delete:
      tags:
        - "Student"
      summary: Delete Student
      parameters:
        - name: studentId
          in: path
          required: true
          description: the student to delete
          schema:
            type: string
      responses:
        '204':
          description: No content
          
        '500':
          description: Server Error  
components:
  schemas:
    StudentsResponse:
      type: object
      properties:
        id: 
          type: string
          example: STD22000
        name:
          type: string
          example: Doe
        birthDate: 
          type: string
          format: date
          example: 2000-12-20  
    AddStudentsResponse:
      type: object
      properties:
        id: 
          type: string
          example: STD22011
        name:
          type: string
          example: John
        birthDate: 
          type: string
          format: date
          example: 2001-02-15
    StudentInput:
      type: object
      properties:
        id: 
          type: string
          example: New ID
        name:
          type: string
          example: NewStudent
        birthDate: 
          type: string
          format: date
          example: Birth date
    TeachersResponse:
      type: array
      items:
        $ref: '#/components/schemas/TeacherResponse'

    TeacherResponse:
      type: object
      properties:
        id:
          type: string
          example: TCH22000
        name:
          type: string
          example: Mr Toky
        specialization:
          type: string
          example: Prog2    
/Teachers:
    get:
      tags:
        - "Teacher"
      summary: Tous les enseignants
      responses:
        '200':
          description: Réussi
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TeachersResponse'

        '500':
          description: Erreur du serveur

    post:
      tags:
        - "Teacher"
      summary: Ajouter un enseignant
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TeacherInput'
      responses:
        '200':
          description: Réussi
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TeacherResponse'

        '500':
          description: Erreur du serveur

